### ISSUE TITLE
BG-3S

### ISSUE THREAD

**Issue by falconmick** [phrederick/sony-bg1s-rgb-mod#1]
Ahoy

Very new to the idea of rgb modding so sorry if this is a dumb one, how much different would a GB-3S be and do you think if I used a combo of the service manual and this docs to try and translate the difference would it likely be possible?

**Comment by phrederick** [comment]
Hey mate - yep you should be able to do the mod with the BG-3S chassis. Here's a video with some more info:
https://www.youtube.com/watch?v=z1zHji1WSy8

Basically BG-1**X**, BG-2**X**, and BG-3**X** (where **X** can be L, S, or R) can all be modified in a very similar fashion.

**Comment by falconmick** [comment]
Thanks! I missed the tv unfortunately couldn't pickup today as daughter is sick and sombody else spotted it! Atleast now I know any 1-2-3 will suit and that they're worth picking up even with only composite as you can mod the RGB
